### ISSUE TITLE
SDK Failing with error (-1910505467) Name Not Found

### ISSUE THREAD

**Issue by kabirkhan** [Microsoft/Cognitive-Speech-STT-Android#6]
This is my log output. Any idea why this is happening? It was working perfectly yesterday and I didn't change anything. Did the api change? 

08-20 23:04:26.817 637-637/com.contosocafe I/System.out: Error Code-1910505467
08-20 23:04:26.817 637-2580/com.contosocafe I/NLPLAT: Message: 'S' has -549604948 remaining transmit attempts.
08-20 23:04:26.817 637-2580/com.contosocafe I/NLPLAT: Retrying message, name='S'
08-20 23:04:26.817 637-2580/com.contosocafe I/NLPLAT: Initiating websocket connection. m_connection=0xe0795024 host=websockets.platform.bing.com port=443
08-20 23:04:26.818 637-2583/com.contosocafe I/NLPLAT: originating error 0x8e200005
08-20 23:04:26.819 637-2580/com.contosocafe I/NLPLAT: originating error 0x80070057
08-20 23:04:26.819 637-2580/com.contosocafe I/NLPLAT: Authorization token hr 80070057 'S' 
08-20 23:04:26.819 637-2580/com.contosocafe I/NLPLAT: Refreshing token S
08-20 23:04:26.819 637-2580/com.contosocafe I/NLPLAT: WSRequest
08-20 23:04:26.819 637-2585/com.contosocafe I/NLPLAT: originating error 0x8e200005
08-20 23:04:26.819 637-2585/com.contosocafe I/NLPLAT: WebSocket closed unexpectedly, status: 0
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: Closing web socket channel
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: CU Client connection dropped
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: ConnectionStateChanged
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: Web socket handshake failed, hr=8E200005
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: web socket message delivery failed, hr=8E200005
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: Web socket channel already closed.
08-20 23:04:26.820 637-2585/com.contosocafe I/NLPLAT: Message: 'S' has -549604948 remaining transmit attempts.

**Comment by loafbaker** [comment]
You need to grant the permission of microphone for your app. Open the app settings on your device and turn it on, then the error would be gone.

**Comment by kabirkhan** [comment]
I already have. I've been working on this app for the last few days and it has always worked until I opened it tonight. I haven't changed any code and the microphone permission is enabled.

**Comment by kabirkhan** [comment]
I think there were internal updates to the Speech API this weekend. Now it works without any changes to my code.

**Comment by jasonvomsft** [comment]
@kabirkhan No changes to the SDK have been made recently. 8e200005 errors typically are due to poor network conditions.

**Comment by amitks2015** [comment]
Any idea what's happening here? There is no issue with permission and network. 

09-15 17:30:55.145 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.145 30615-31592/? I/NLPLAT: Authorization token hr 80070057 'S' 
09-15 17:30:55.147 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.147 30615-31592/? I/NLPLAT: originating error 0x80070057
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Audio stream created
09-15 17:30:55.148 30615-31592/? I/NLPLAT: Adding requestId: 'S' for '8'
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Subscribing request [S]
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Audio Stream Created
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Creating transcoder 2
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Setting format for audio stream, 00000001
09-15 17:30:55.149 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.150 30615-31592/? I/NLPLAT: Sent first chunk of audio stream, requestId='84aa3f08-4341-30d1-ca1a-a634276ffaa6'
09-15 17:30:55.170 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.191 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.213 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.233 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.254 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.275 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.296 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.317 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.338 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: WebSocket closed unexpectedly, status: 0
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Closing web socket channel
09-15 17:30:55.356 30615-10021/? I/NLPLAT: CU Client connection dropped
09-15 17:30:55.356 30615-10021/? I/NLPLAT: ConnectionStateChanged
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Upgrade request returned with HTTP status code: 403.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Web socket handshake failed, hr=8E200002
09-15 17:30:55.356 30615-10021/? I/NLPLAT: web socket message delivery failed, hr=8E200002
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Web socket channel already closed.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Message: 'S' has -1712124788 remaining transmit attempts.
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Retrying message, name='S'
09-15 17:30:55.356 30615-10021/? I/NLPLAT: Initiating websocket connection. m_connection=0x9a050a74 host=websockets.platform.bing.com port=443
09-15 17:31:00.153 799-25738/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=21811837, 10.251.225.1, [24BE05F2A300], RTM_NEWNEIGH, NUD_REACHABLE}
09-15 17:31:09.103 799-25738/? D/NetlinkSocketObserver: NeighborEvent{elapsedMs=21820788, 10.251.225.1, [24BE05F2A300], RTM_NEWNEIGH, NUD_STALE}
09-15 17:31:10.357 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.357 30615-10021/? I/NLPLAT: Authorization token hr 80070057 'S' 
09-15 17:31:10.365 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.365 30615-10021/? I/NLPLAT: originating error 0x80070057
09-15 17:31:10.366 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.367 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.367 30615-10021/? I/NLPLAT: WSRequest
09-15 17:31:10.387 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.409 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.430 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.451 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.473 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.494 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.515 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.536 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.557 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.578 30615-31592/? I/NLPLAT: Waiting for connection/send completion.
09-15 17:31:10.597 30615-10030/? I/NLPLAT: WebSocket closed unexpectedly, status: 0
09-15 17:31:10.597 30615-10030/? I/NLPLAT: Closing web socket channel
09-15 17:31:10.597 30615-10030/? I/NLPLAT: CU Client connection dropped
09-15 17:31:10.597 30615-10030/? I/NLPLAT: ConnectionStateChanged
09-15 17:31:10.597 30615-10030/? I/NLPLAT: Upgrade request returned with HTTP status code: 403.

Can I use same key with two different application? Can this issue occur because I am using same key with test application provided here?
